spring:
  datasource:
    url: jdbc:sqlite:mydb.sqlite #mydb.sqlite is the name of the SQLite file. If you don?t have the file (at the project?s root), it will be automatically created.
    username: admin
    password: admin
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 30
      pool-name: "[mydb-pool]"
  sql:
    init:
      mode: always
logging:
  level:
    root: info
    org.mybatis: debug
    org.xerial: debug
    com.zaxxer.hikari: debug
    com.tistory.aircook.mybatis.repository.PeopleSimpleRepository: debug
    com.tistory.aircook.mybatis: debug
mybatis:
  #mapper-locations: mapper/**/*.xml #mapper.xml 위치 지정
  #type-aliases-package: com.tistory.aircook.mybatis.domain #패키지 명을 생략할 수 있도록 alias 설정
  configuration:
    map-underscore-to-camel-case: true