DROP TABLE IF EXISTS PEOPLES;

CREATE TABLE PEOPLES
(
    ID    INTEGER PRIMARY KEY, /* Integer타입의 필드에 고유값 속성만 주면 알아서 AUTO_INCREMENT속성을 준것과 같이 동작 */
    NAME  VARCHAR(50),
    BIRTH VARCHAR(20)
);

DROP TABLE IF EXISTS MEMOS;

CREATE TABLE MEMOS
(
    ID       INTEGER PRIMARY KEY,
    MEMO     VARCHAR(300),
    WRITER   VARCHAR(100),
    WRITE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
